### ISSUE TITLE
GitHub-Crud

### ISSUE THREAD

**Issue by philiprbrenan** [szabgab/github-actions#1]
Please consider using/developing:

https://metacpan.org/release/GitHub-Crud

to automate all interactions with GitHub such as:

listRepositories - to list all repositories owned by a user
list                     - to list all files in a repository
read                  - to read a file

**Comment by szabgab** [comment]
Thanks for the suggestion, but it would be probably more relevant to the https://github.com/szabgab/cpan-digger-new project which is written in Perl.
